steps:
  - name: maven:3-openjdk-17
    entrypoint: mvn
    args: ["clean", "package", "-Dimage=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_ARTIFACT_CLOUD}:${_VERSION}"]
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:slim'
    args: ["gcloud", "dataflow", "flex-template", "build",
           "gs://${_BUCKET}/${_VERSION}",
           "--image", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_ARTIFACT_CLOUD}:${_VERSION}",
           "--sdk-language", "JAVA"]
  - name: docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_ARTIFACT_LOCAL}:${_VERSION}", "."]
  - name: docker
    args: ["push", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_ARTIFACT_LOCAL}:${_VERSION}"]
substitutions:
  _BUCKET: "{SET YOUR BUCKET}"
  _REGION: "{SET YOUR GAR REPOSITORY REGION}"
  _REPOSITORY: "{SET YOUR GAR REPOSITORY NAME}"
  _ARTIFACT_CLOUD: "{SET YOUR GAR REPOSITORY ARTIFACT NAME}"
  _ARTIFACT_LOCAL: "{SET YOUR GAR REPOSITORY ARTIFACT NAME FOR LOCAL TYPE}"
  _VERSION: ${BRANCH_NAME}
options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY