steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ["cp", "gs://examble-bucket/neo4j/index/transaction.zip", "."]
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: "unzip"
    args: ["transaction.zip"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build",
           "-f", "Dockerfile_graph",
           "-t", "$_REGION-docker.pkg.dev/$PROJECT_ID/graph/graph",
           "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "$_REGION-docker.pkg.dev/$PROJECT_ID/graph/graph"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ["run", "deploy", "graph",
           "--image", "$_REGION-docker.pkg.dev/$PROJECT_ID/graph/graph",
           "--platform", "managed",
           "--region", "$_REGION",
           "--memory", "2Gi",
           "--port", "7474",
           "--min-instances", "1",
           "--no-allow-unauthenticated"]
timeout: 600s
substitutions:
  _REGION: asia-northeast1